language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-project-template
  - make -j
  - cd ./bin/
  - ./test_mp2
notifications:
  email: false
